# SPDX-FileCopyrightText: 2026 Exocomp contributors
# SPDX-License-Identifier: Apache-2.0
defmodule Exocomp.MissionControl.Organizations do
  @moduledoc "The organization identity boundary."

  alias Exocomp.MissionControl.{Organization, Repo}

  @doc "Builds a new organization with a generated, stable UUID."
  @spec new(map()) :: Ecto.Changeset.t()
  def new(attrs) when is_map(attrs) do
    %Organization{id: Ecto.UUID.generate()}
    |> Organization.changeset(attrs)
  end

  @doc "Creates an organization. IDs are generated by this boundary."
  @spec create(map(), keyword()) :: {:ok, Organization.t()} | {:error, Ecto.Changeset.t()}
  def create(attrs, opts \\ []) when is_map(attrs) do
    repo = Keyword.get(opts, :repo, Repo)
    repo.insert(new(attrs))
  end

  @doc "Fetches an organization by its stable ID."
  @spec get(Ecto.UUID.t(), keyword()) :: Organization.t() | nil
  def get(id, opts \\ []) do
    repo = Keyword.get(opts, :repo, Repo)
    repo.get(Organization, id)
  end

  @doc "Fetches an organization by its unique slug."
  @spec get_by_slug(String.t(), keyword()) :: Organization.t() | nil
  def get_by_slug(slug, opts \\ []) when is_binary(slug) do
    repo = Keyword.get(opts, :repo, Repo)
    repo.get_by(Organization, slug: slug)
  end
end
