#!/usr/bin/env bash
# install.sh — Hardened exocomp node/coordinator installer.
#
# Run from inside an extracted exocomp release bundle as root:
#
#   sudo bash scripts/install.sh --component node [OPTIONS]
#
# OPTIONS
#   --component  node|coordinator         (required)
#   --bundle     PATH                     release archive (.tar.gz)
#                                         default: auto-detect from bundle directory
#   --checksums  PATH                     SHA-256 checksums file
#                                         default: <bundle-dir>/checksums.sha256
#   --version    VERSION                  override version detected from archive
#   --allow-list SVC1,SVC2,...            comma-separated systemd service names
#                                         granted in the sudoers policy
#                                         (empty = no privileged service entries)
#   --no-start                            install but do not start the service
#   --non-interactive                     never prompt; fail on ambiguity
#   --dry-run                             validate only, no host mutation
#
# ENVIRONMENT OVERRIDES (for testing without root or systemd)
#   EXOCOMP_ROOT         Prefix prepended to /opt, /etc, /var paths (default: "")
#   EXOCOMP_SYSTEMD_DIR  Full path to systemd unit directory
#                        (default: ${EXOCOMP_ROOT}/etc/systemd/system)
#   EXOCOMP_SUDOERS_DIR  Full path to sudoers drop-in directory
#                        (default: ${EXOCOMP_ROOT}/etc/sudoers.d)
#   EXOCOMP_SKIP_SYSTEMD Set to "1" to skip all systemctl calls
#   EXOCOMP_SKIP_VISUDO  Set to "1" to skip visudo validation

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────

COMPONENT=""
BUNDLE=""
CHECKSUMS_FILE=""
VERSION=""
ALLOW_LIST=""
NO_START=0
NON_INTERACTIVE=0
DRY_RUN=0

EXOCOMP_ROOT="${EXOCOMP_ROOT:-}"
EXOCOMP_SKIP_SYSTEMD="${EXOCOMP_SKIP_SYSTEMD:-0}"
EXOCOMP_SKIP_VISUDO="${EXOCOMP_SKIP_VISUDO:-0}"
# When EXOCOMP_ROOT is non-empty we are in a test/sandbox environment; skip
# operations that require real root: useradd, chown.
EXOCOMP_SKIP_USERADD="${EXOCOMP_SKIP_USERADD:-${EXOCOMP_ROOT:+1}}"
EXOCOMP_SKIP_CHOWN="${EXOCOMP_SKIP_CHOWN:-${EXOCOMP_ROOT:+1}}"

# Resolve script and bundle directories.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(dirname "${SCRIPT_DIR}")"

# ── Argument parsing ───────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --component)      COMPONENT="$2";      shift 2 ;;
        --bundle)         BUNDLE="$2";         shift 2 ;;
        --checksums)      CHECKSUMS_FILE="$2"; shift 2 ;;
        --version)        VERSION="$2";        shift 2 ;;
        --allow-list)     ALLOW_LIST="$2";     shift 2 ;;
        --no-start)       NO_START=1;          shift   ;;
        --non-interactive) NON_INTERACTIVE=1;  shift   ;;
        --dry-run)        DRY_RUN=1;           shift   ;;
        *)
            echo "ERROR: Unknown option: $1" >&2
            echo "Usage: sudo bash $0 --component node|coordinator [OPTIONS]" >&2
            exit 1
            ;;
    esac
done

# ── Derived paths ──────────────────────────────────────────────────────────────

EXOCOMP_SYSTEMD_DIR="${EXOCOMP_SYSTEMD_DIR:-${EXOCOMP_ROOT}/etc/systemd/system}"
EXOCOMP_SUDOERS_DIR="${EXOCOMP_SUDOERS_DIR:-${EXOCOMP_ROOT}/etc/sudoers.d}"
INSTALL_BASE="${EXOCOMP_ROOT}/opt/exocomp"

# ── Helpers ───────────────────────────────────────────────────────────────────

log()  { echo "[install] $*"; }
warn() { echo "[install] WARN: $*" >&2; }
die()  { echo "[install] ERROR: $*" >&2; exit 1; }

require_root() {
    # Skip root check when running in sandbox/test mode
    if [[ -n "${EXOCOMP_ROOT}" || "${EXOCOMP_SKIP_SYSTEMD}" == "1" ]]; then
        return
    fi
    if [[ "$(id -u)" -ne 0 ]]; then
        die "must be run as root (try: sudo $0)"
    fi
}

# Wrapper for chown: no-op in test/sandbox mode
do_chown() {
    if [[ "${EXOCOMP_SKIP_CHOWN}" == "1" ]]; then
        return
    fi
    chown "$@"
}

# Wrapper for chmod: always runs (no privilege required)
do_chmod() {
    chmod "$@"
}

# Render exact sudoers policy for the given account and allow-list.
# Matches the format generated by Exocomp.Node.SudoersPolicy.
render_sudoers() {
    local account="$1"
    local allow_list="$2"  # comma-separated service names
    local vacuum_size="${3:-100M}"

    # Validate account: alphanumeric + underscore + hyphen, starting with letter/underscore
    if ! echo "${account}" | grep -qE '^[a-zA-Z_][a-zA-Z0-9_-]*$'; then
        die "invalid account name for sudoers: '${account}'"
    fi

    local entries=()

    # Add restart entries for each allow-listed service
    if [[ -n "${allow_list}" ]]; then
        IFS=',' read -ra services <<< "${allow_list}"
        for svc in "${services[@]}"; do
            svc="$(echo "${svc}" | tr -d '[:space:]')"
            # Validate service name: alphanumeric + hyphen + underscore + dot + @ only
            # Must start with alphanumeric; optional .service suffix
            if ! echo "${svc}" | grep -qE '^[a-zA-Z0-9][a-zA-Z0-9._@-]*(.service)?$'; then
                die "invalid service name for sudoers: '${svc}'"
            fi
            entries+=("/usr/bin/systemctl restart ${svc}")
        done
    fi

    # Add vacuum entry
    entries+=("/usr/bin/journalctl --vacuum-size=${vacuum_size}")

    if [[ ${#entries[@]} -eq 0 ]]; then
        echo ""
        return
    fi

    cat <<SUDOERS_HEADER
# Exocomp node sudoers policy
# Generated for account: ${account}
# DO NOT EDIT — regenerate from the installed action catalog.
# Validate with: visudo -c -f ${EXOCOMP_SUDOERS_DIR}/${account}
SUDOERS_HEADER

    for entry in "${entries[@]}"; do
        echo "${account} ALL=(root) NOPASSWD: ${entry}"
    done
}

# Write file contents only if in non-dry-run mode.
install_file() {
    local content="$1"
    local dest="$2"
    local mode="${3:-644}"
    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would write ${dest} (mode ${mode})"
        return
    fi
    mkdir -p "$(dirname "${dest}")"
    printf '%s' "${content}" > "${dest}"
    chmod "${mode}" "${dest}"
}

# ── Phase 1: PREFLIGHT (no host mutation) ────────────────────────────────────

preflight() {
    log "==> PREFLIGHT"

    # 1a. Validate required --component flag
    if [[ -z "${COMPONENT}" ]]; then
        die "--component node|coordinator is required"
    fi
    if [[ "${COMPONENT}" != "node" && "${COMPONENT}" != "coordinator" ]]; then
        die "--component must be 'node' or 'coordinator'; got '${COMPONENT}'"
    fi

    # 1b. Determine release archive
    if [[ -z "${BUNDLE}" ]]; then
        # Auto-detect: look for exocomp-<component>-*.tar.gz in bundle root
        local matches
        matches=("${BUNDLE_ROOT}"/exocomp-"${COMPONENT}"-*.tar.gz)
        if [[ ${#matches[@]} -eq 0 ]] || [[ ! -f "${matches[0]}" ]]; then
            die "no release archive found in ${BUNDLE_ROOT}; pass --bundle PATH"
        fi
        if [[ ${#matches[@]} -gt 1 ]]; then
            die "multiple release archives found; pass --bundle PATH to choose one"
        fi
        BUNDLE="${matches[0]}"
    fi
    if [[ ! -f "${BUNDLE}" ]]; then
        die "bundle not found: ${BUNDLE}"
    fi
    log "  bundle:    ${BUNDLE}"

    # 1c. Determine version from archive name if not given
    if [[ -z "${VERSION}" ]]; then
        VERSION="$(basename "${BUNDLE}" | sed -E 's/^exocomp-[^-]+-([0-9]+\.[0-9]+\.[0-9]+[^.]*)-.*\.tar\.gz$/\1/' 2>/dev/null || true)"
        if [[ -z "${VERSION}" ]]; then
            die "cannot determine version from archive name; pass --version VERSION"
        fi
    fi
    # Validate version: semver-like (digits + dots + optional prerelease)
    if ! echo "${VERSION}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+'; then
        die "invalid version '${VERSION}'; expected semver (e.g. 1.2.3)"
    fi
    log "  version:   ${VERSION}"
    log "  component: ${COMPONENT}"

    # 1d. Validate host architecture
    local arch
    arch="$(uname -m)"
    if [[ "${arch}" != "x86_64" && "${arch}" != "aarch64" ]]; then
        die "unsupported architecture '${arch}'; supported: x86_64, aarch64"
    fi
    log "  arch:      ${arch}"

    # 1e. Validate checksums
    if [[ -z "${CHECKSUMS_FILE}" ]]; then
        CHECKSUMS_FILE="${BUNDLE_ROOT}/checksums.sha256"
    fi
    if [[ ! -f "${CHECKSUMS_FILE}" ]]; then
        # Warn but allow if no checksums file (e.g. dev install)
        warn "checksums file not found: ${CHECKSUMS_FILE} (skipping verification)"
    else
        log "  checksums: ${CHECKSUMS_FILE}"
        verify_checksums
    fi

    # 1f. Check available disk space (require 2 GiB free in install base)
    local install_dir
    install_dir="$(dirname "${INSTALL_BASE}")"
    if ! check_disk_space "${install_dir}" 2147483648; then
        die "insufficient disk space; need at least 2 GiB free in ${install_dir}"
    fi

    # 1g. Check systemd availability
    if [[ "${EXOCOMP_SKIP_SYSTEMD}" != "1" ]]; then
        if ! command -v systemctl >/dev/null 2>&1; then
            die "systemctl not found; run inside a system with systemd as PID 1"
        fi
        if ! systemctl is-system-running --quiet 2>/dev/null && \
           ! systemctl status --quiet 2>/dev/null; then
            warn "systemd may not be fully running (booting or degraded)"
        fi
    fi

    # 1h. Verify systemd unit template exists in bundle
    local unit_template="${BUNDLE_ROOT}/release/${COMPONENT}/exocomp-${COMPONENT}.service"
    if [[ ! -f "${unit_template}" ]]; then
        die "systemd unit template not found in bundle: ${unit_template}"
    fi

    log "  preflight passed"
}

verify_checksums() {
    log "  verifying checksums..."
    local bundle_basename
    bundle_basename="$(basename "${BUNDLE}")"

    # Extract relevant line from checksums file
    local expected_line
    expected_line="$(grep -F "${bundle_basename}" "${CHECKSUMS_FILE}" 2>/dev/null || true)"
    if [[ -z "${expected_line}" ]]; then
        die "no checksum entry for '${bundle_basename}' in ${CHECKSUMS_FILE}"
    fi

    # Compute actual checksum
    local actual_hash
    actual_hash="$(sha256sum "${BUNDLE}" | awk '{print $1}')"
    local expected_hash
    expected_hash="$(echo "${expected_line}" | awk '{print $1}')"

    if [[ "${actual_hash}" != "${expected_hash}" ]]; then
        die "checksum MISMATCH for ${bundle_basename}
         expected: ${expected_hash}
         actual:   ${actual_hash}"
    fi
    log "  checksum OK: ${actual_hash}"
}

check_disk_space() {
    local dir="$1"
    local required_bytes="$2"

    # Create dir if it doesn't exist yet (for check purposes only)
    local check_dir="${dir}"
    while [[ ! -d "${check_dir}" ]]; do
        check_dir="$(dirname "${check_dir}")"
    done

    local available_bytes
    available_bytes="$(df --output=avail -B1 "${check_dir}" 2>/dev/null | tail -1 | tr -d '[:space:]' || echo "0")"
    if [[ "${available_bytes}" -ge "${required_bytes}" ]]; then
        return 0
    else
        return 1
    fi
}

# ── Phase 2: USER AND DIRECTORY SETUP ─────────────────────────────────────────

setup_users_and_dirs() {
    log "==> USERS AND DIRECTORIES"

    local account="exocomp-${COMPONENT}"
    local install_dir="${INSTALL_BASE}/${COMPONENT}"
    local releases_dir="${install_dir}/releases"
    local config_dir="${install_dir}/config"
    local log_dir="${install_dir}/log"
    local pki_dir="${config_dir}/pki"
    local var_dir="${EXOCOMP_ROOT}/var/lib/exocomp-${COMPONENT}"

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would create user ${account} and directories"
        return
    fi

    # Create dedicated system user if not exists
    if [[ "${EXOCOMP_SKIP_USERADD}" == "1" ]]; then
        log "  [skip-useradd] skipping system user creation (test/sandbox mode)"
    elif ! id "${account}" >/dev/null 2>&1; then
        log "  creating system user: ${account}"
        useradd \
            --system \
            --no-create-home \
            --shell /usr/sbin/nologin \
            --comment "exocomp ${COMPONENT} service account" \
            "${account}"
    else
        log "  user exists: ${account}"
    fi

    # Create directory structure
    log "  creating directories"
    mkdir -p "${releases_dir}"
    mkdir -p "${config_dir}"
    mkdir -p "${log_dir}"
    mkdir -p "${pki_dir}"
    mkdir -p "${var_dir}"

    # Set ownership and permissions
    # Releases dir: owned by root, readable by service account
    do_chown -R root:root "${install_dir}"
    do_chown "${account}:${account}" "${config_dir}"
    do_chown "${account}:${account}" "${log_dir}"
    do_chown "${account}:${account}" "${pki_dir}"
    do_chown "${account}:${account}" "${var_dir}"

    # Strict permissions
    do_chmod 755  "${install_dir}"
    do_chmod 755  "${releases_dir}"
    do_chmod 750  "${config_dir}"
    do_chmod 750  "${log_dir}"
    do_chmod 700  "${pki_dir}"
    do_chmod 750  "${var_dir}"

    log "  directories configured"
}

# ── Phase 3: INSTALL RELEASE ──────────────────────────────────────────────────

install_release() {
    log "==> INSTALL RELEASE"

    local account="exocomp-${COMPONENT}"
    local install_dir="${INSTALL_BASE}/${COMPONENT}"
    local versioned_dir="${install_dir}/releases/${VERSION}"
    local current_link="${install_dir}/current"

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would extract ${BUNDLE} to ${versioned_dir}"
        return
    fi

    # Check for existing version (idempotent: overwrite if same version)
    if [[ -d "${versioned_dir}" ]]; then
        log "  version ${VERSION} already installed; overwriting"
        # Make writable before removal (previous install set a-w on contents)
        chmod -R u+w "${versioned_dir}" 2>/dev/null || true
        rm -rf "${versioned_dir}"
    fi

    # Extract release archive
    log "  extracting ${BUNDLE}"
    mkdir -p "${versioned_dir}"
    tar -xzf "${BUNDLE}" -C "${versioned_dir}" --strip-components=1

    # Set ownership: root owns the release; service account has read access
    do_chown -R root:root "${versioned_dir}"
    # Lock down release files: no write access except to root owner.
    # chmod does not require root so we always apply it.
    chmod -R a-w "${versioned_dir}"   # No write access to release files
    chmod -R o+rX "${versioned_dir}"  # Others can read/traverse

    # Make release entrypoints executable
    if [[ -d "${versioned_dir}/bin" ]]; then
        chmod -R a+rX "${versioned_dir}/bin"
    fi

    # Atomic version link.
    # Use a temp symlink + rename to avoid exposing an absent `current` link
    # during the switchover.  `mv -f` on a path where a *file* already exists
    # replaces it; however when `current` is a symlink that itself points to a
    # *directory*, some `mv` implementations traverse the symlink and treat the
    # parent dir as the destination.  To avoid that, remove any existing
    # `current` file/symlink before the rename.
    log "  creating atomic current link -> releases/${VERSION}"
    local tmp_link
    tmp_link="${current_link}.new.$$"
    ln -sf "releases/${VERSION}" "${tmp_link}"
    # Remove old link/file, then rename atomically (best-effort on Linux)
    rm -f "${current_link}"
    mv -f "${tmp_link}" "${current_link}"

    log "  release ${VERSION} installed"
}

# ── Phase 4: CONFIGURATION TEMPLATE ──────────────────────────────────────────

install_config() {
    log "==> CONFIGURATION"

    local install_dir="${INSTALL_BASE}/${COMPONENT}"
    local config_dir="${install_dir}/config"
    local config_file="${config_dir}/${COMPONENT}.json"
    local template_src="${BUNDLE_ROOT}/release/templates/${COMPONENT}.json"

    if [[ ! -f "${template_src}" ]]; then
        die "config template not found in bundle: ${template_src}"
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would install config template to ${config_file}"
        return
    fi

    if [[ -f "${config_file}" ]]; then
        log "  config exists; preserving (not overwriting): ${config_file}"
    else
        log "  installing config template: ${config_file}"
        cp "${template_src}" "${config_file}"
        do_chown "exocomp-${COMPONENT}:exocomp-${COMPONENT}" "${config_file}"
        do_chmod 640 "${config_file}"
    fi
}

# ── Phase 5: SUDOERS POLICY ───────────────────────────────────────────────────

install_sudoers() {
    log "==> SUDOERS POLICY"

    local account="exocomp-${COMPONENT}"
    local sudoers_dest="${EXOCOMP_SUDOERS_DIR}/${account}"
    local policy
    policy="$(render_sudoers "${account}" "${ALLOW_LIST}")"

    if [[ -z "${policy}" ]]; then
        log "  allow-list is empty; no sudoers entries installed"
        # Remove any existing stale policy file
        if [[ "${DRY_RUN}" -ne 1 ]] && [[ -f "${sudoers_dest}" ]]; then
            log "  removing stale sudoers file: ${sudoers_dest}"
            rm -f "${sudoers_dest}"
        fi
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would write sudoers policy:"
        echo "${policy}" | sed 's/^/    /'
        return
    fi

    mkdir -p "${EXOCOMP_SUDOERS_DIR}"
    # Remove existing file first (it may be read-only from a prior install)
    rm -f "${sudoers_dest}"
    echo "${policy}" > "${sudoers_dest}"
    do_chmod 440 "${sudoers_dest}"
    do_chown root:root "${sudoers_dest}"

    # Validate with visudo if available and not skipped
    if [[ "${EXOCOMP_SKIP_VISUDO}" != "1" ]] && command -v visudo >/dev/null 2>&1; then
        log "  validating with visudo..."
        if ! visudo -c -f "${sudoers_dest}" 2>&1; then
            rm -f "${sudoers_dest}"
            die "sudoers validation failed; policy file removed"
        fi
        log "  visudo check passed"
    fi

    log "  sudoers policy installed: ${sudoers_dest}"
}

# ── Phase 6: SYSTEMD UNIT ────────────────────────────────────────────────────

install_systemd_unit() {
    log "==> SYSTEMD UNIT"

    local unit_name="exocomp-${COMPONENT}"
    local unit_src="${BUNDLE_ROOT}/release/${COMPONENT}/${unit_name}.service"
    local unit_dest="${EXOCOMP_SYSTEMD_DIR}/${unit_name}.service"

    if [[ ! -f "${unit_src}" ]]; then
        die "systemd unit not found: ${unit_src}"
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would install unit file: ${unit_dest}"
        return
    fi

    mkdir -p "${EXOCOMP_SYSTEMD_DIR}"

    # Substitute install path in unit file
    local install_dir="${INSTALL_BASE}/${COMPONENT}"
    sed \
        -e "s|@INSTALL_DIR@|${install_dir}|g" \
        -e "s|@COMPONENT@|${COMPONENT}|g" \
        -e "s|@ACCOUNT@|exocomp-${COMPONENT}|g" \
        -e "s|@VERSION@|${VERSION}|g" \
        "${unit_src}" > "${unit_dest}"

    do_chmod 644 "${unit_dest}"
    do_chown root:root "${unit_dest}"

    log "  unit installed: ${unit_dest}"
}

# ── Phase 7: ACTIVATE SERVICE ─────────────────────────────────────────────────

activate_service() {
    log "==> ACTIVATE"

    local unit_name="exocomp-${COMPONENT}"

    if [[ "${EXOCOMP_SKIP_SYSTEMD}" == "1" ]]; then
        log "  [skip-systemd] skipping daemon-reload and service start"
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would enable and start ${unit_name}.service"
        return
    fi

    log "  systemctl daemon-reload"
    systemctl daemon-reload

    log "  systemctl enable ${unit_name}"
    systemctl enable "${unit_name}"

    if [[ "${NO_START}" -eq 1 ]]; then
        log "  --no-start set; skipping service start"
        return
    fi

    if systemctl is-active --quiet "${unit_name}" 2>/dev/null; then
        log "  systemctl restart ${unit_name}  (already running)"
        systemctl restart "${unit_name}"
    else
        log "  systemctl start ${unit_name}"
        systemctl start "${unit_name}"
    fi

    log "  service active"
    systemctl status "${unit_name}" --no-pager --lines=5 || true
}

# ── Phase 8: WRITE MANIFEST ───────────────────────────────────────────────────

write_manifest() {
    log "==> MANIFEST"

    local install_dir="${INSTALL_BASE}/${COMPONENT}"
    local unit_name="exocomp-${COMPONENT}"
    local account="exocomp-${COMPONENT}"
    local manifest_file="${install_dir}/manifest-${VERSION}.txt"
    local var_dir="${EXOCOMP_ROOT}/var/lib/${account}"

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "  [dry-run] would write manifest: ${manifest_file}"
        return
    fi

    cat > "${manifest_file}" <<MANIFEST
# Exocomp installed-file manifest
# Component: ${COMPONENT}
# Version: ${VERSION}
# Installed: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Account: ${account}
#
# Files and directories managed by this installation.
# The uninstaller reads this manifest to identify exocomp-owned resources.
#
# PROTECTED paths (never removed by default uninstall):
#   ${install_dir}/config/
#   ${install_dir}/log/
#   ${var_dir}/
#
# Remove only if --purge category is specified.

# Systemd unit
${EXOCOMP_SYSTEMD_DIR}/${unit_name}.service

# Sudoers policy (if installed)
$(if [[ -n "${ALLOW_LIST}" ]]; then echo "${EXOCOMP_SUDOERS_DIR}/${account}"; fi)

# Current version symlink
${install_dir}/current

# Versioned release directory
${install_dir}/releases/${VERSION}/

# Manifest (this file — removed by uninstaller)
${manifest_file}
MANIFEST

    do_chmod 644 "${manifest_file}"
    do_chown root:root "${manifest_file}"

    log "  manifest written: ${manifest_file}"
}

# ── Main ──────────────────────────────────────────────────────────────────────

main() {
    require_root
    preflight
    setup_users_and_dirs
    install_release
    install_config
    install_sudoers
    install_systemd_unit
    activate_service
    write_manifest

    echo ""
    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "==> DRY RUN COMPLETE — no host mutations were made"
    else
        log "==> exocomp-${COMPONENT} ${VERSION} installed successfully"
        if [[ "${NO_START}" -eq 0 && "${EXOCOMP_SKIP_SYSTEMD}" != "1" ]]; then
            log "    service: exocomp-${COMPONENT}.service (active)"
        fi
        log "    install: ${INSTALL_BASE}/${COMPONENT}"
        log "    config:  ${INSTALL_BASE}/${COMPONENT}/config/${COMPONENT}.json"
        log "    log:     ${INSTALL_BASE}/${COMPONENT}/log/"
    fi
}

main
